name: Organization-Wide Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, nixos-server] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'current_app' 

      - name: Deploy
        run: |
          mkdir -p ${{ vars.DEPLOY_PATH }}
          
          # Synchronize checked out code to the permanent folder
          cp -R ./current_app/* ${{ vars.DEPLOY_PATH }}/
          
          cd ${{ vars.DEPLOY_PATH }}
          
          docker-compose up -d --build
          docker image prune -f